GET http://localhost:5500/ul73yoiblrhp02d8eag2

###

POST http://localhost:5500/ul73yoiblrhp02d8eag2
Content-Type: application/json

{
    "username": "dark",
    "email": "darkshadow@gmail.com",
    "password": "123"
}